{"name": "test_6", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 10 > 20", "trace": "@pytest.mark.xfail\n    def test_6():\n        a = 10\n        b = 20\n    \n>       assert a > b  # xfailed\nE       assert 10 > 20\n\nSeleniumProgram\\test_markers.py:51: AssertionError"}, "start": 1673445930383, "stop": 1673445930383, "uuid": "ff07d9d6-f204-4d74-bef7-afe71d54308f", "historyId": "9d03cf3521012e9ee6c3e597d9d46c2d", "testCaseId": "40767d43dbbd46bc0fa4df4b2b2e73ca", "fullName": "test_markers#test_6", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_markers"}, {"name": "host", "value": "HP"}, {"name": "thread", "value": "45852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_markers"}]}