{"name": "test_6", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 10 > 20", "trace": "@pytest.mark.xfail\n    def test_6():\n        a = 10\n        b = 20\n    \n>       assert a > b    # xfailed\nE       assert 10 > 20\n\nSeleniumProgram\\test_markers.py:51: AssertionError"}, "start": 1672762896551, "stop": 1672762896552, "uuid": "27af35ff-5d4e-49a5-b9a3-c67e821921b2", "historyId": "9d03cf3521012e9ee6c3e597d9d46c2d", "testCaseId": "40767d43dbbd46bc0fa4df4b2b2e73ca", "fullName": "test_markers#test_6", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_markers"}, {"name": "host", "value": "HP"}, {"name": "thread", "value": "24940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_markers"}]}