{"name": "test_sub_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 10", "trace": "def test_sub_1():\n        x = 10\n        y = 10\n        result = x - y\n>       assert result == 10\nE       assert 0 == 10\n\nSeleniumProgram\\test_second_program.py:19: AssertionError"}, "start": 1673446088206, "stop": 1673446088206, "uuid": "e73d2925-bd07-4399-a75d-fda55c286a10", "historyId": "7fbfbf39e6612218181a53a667743a08", "testCaseId": "74a6e9401e144370a6da17657e925955", "fullName": "test_second_program#test_sub_1", "labels": [{"name": "suite", "value": "test_second_program"}, {"name": "host", "value": "HP"}, {"name": "thread", "value": "33596-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_second_program"}]}